### PR TITLE
Small syntax changes 'Lists' thru 'Declaration Sorting'

### PR DESCRIPTION
**Pull request by mdouglasbrett**
Hi Hugo,

Hope this PR is more straightforward than last time! I've changed a slight bit of sentence structure.

Thanks for being patient with my git amateurishness :)

Best,

Mike

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Before submitting a PR, always be sure to [sync your fork](https://help.github.com/articles/syncing-a-fork/) Mike. Would you care giving it a try then submitting your PR again?

**Comment by mdouglasbrett** [comment]
Hi Hugo

Once I have merged the upstream/master, do I have to do a push to origin/master (and will this take care of the gh-pages branch)?

Sorry to be a pain in the bum

Michael Brett

**Comment by HugoGiraudel** [comment]
Yep, do this. I think it should be good this way.

**Comment by mdouglasbrett** [comment]
Hi Hugo

I have pushed to origin/master. I can't do another pull request on the gh-pages branch but can on master. Shall I proceed?

**Comment by HugoGiraudel** [comment]
Nope. Let's close this one so you can PR on gh-pages. :)

**Pull request closed without merging**
