### PR TITLE
[WIP] Persian translation

### PR DESCRIPTION
**Pull request by Mojtabarahimi8**
# Translation Progress
## Basic
- [x] `_data/translations.yml`
- [x] `_data/languages.yml`
## Code (comments only)
- [ ] `_includes/snippets`
## Readme
- [x] `README.md`
## Content
- [ ] `_architecture.md`
- [ ] `_author.md`
- [ ] `_comments.md`
- [ ] `_conditions.md`
- [ ] `_contributing.md`
- [ ] `_errors.md`
- [ ] `_extend.md`
- [ ] `_introduction.md`
- [ ] `_loops.md`
- [ ] `_mixins.md`
- [ ] `_naming.md`
- [ ] `_rwd.md`
- [ ] `_sass.md`
- [ ] `_syntax.md`
- [ ] `_tldr.md`
- [ ] `_toc.md`
- [ ] `_tools.md`
- [ ] `_variables.md`

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
All good! :)

**Comment by HugoGiraudel** [comment]
Hey there. What is the current status on this? :)

**Comment by HugoGiraudel** [comment]
Hey there. Little reminder that version 1.3 has been released! 🎉

You can either keep going on 1.2, then we merge, then you work on 1.3. Or go straight to 1.3 right away. It’s really up to you.

On topic, do you need me to find you any support on this? Or do you think you could find time and energy to finish it on your own? :)

**Comment by HugoGiraudel** [comment]
Hey @Mojtabarahimi8. Is there any progress on this? Are you willing to continue or shall I close it? :)

**Comment by Mojtabarahimi8** [comment]
hey hugo, i will because i got into a project i didnt have time, i translate many parts, i pull them , hope to get some more time to finish it

    On Monday, August 15, 2016 2:32 AM, Hugo Giraudel <notifications@github.com> wrote:
 

 Hey @Mojtabarahimi8. Is there any progress on this? Are you willing to continue or shall I close it? :)—

**Comment by HugoGiraudel** [comment]
Hi! Shall I close this? :)

**Pull request closed without merging**
