### PR TITLE
fix and update RU

### PR DESCRIPTION
**Pull request by Grawl**
fix some language-dependent errors
fix one TOC link
upgrade readability
remove extra blank lines everywhere
something more… I tried, cannot remember all the things I do last two
hours.

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Mpf.. Blank lines actually help readibility when updating content.

**Comment by HugoGiraudel** [comment]
I suppose since you are the one maintaining the Russian translation, I can let you do the way you want.

**Comment by HugoGiraudel** [comment]
Thank you very much. :)

**Comment by Grawl** [comment]
I don't like extra syntax at all. I can accept only two blank lines in a row but not more. Perfectionism.
I'm glad to be a part of such a great thing like Sass Guidelines. It's awesome experience.

**Comment by HugoGiraudel** [comment]
Let me be honest with you and tell you that I am glad to see you as a contributor for the Russian version. It is one of the most robust of all so far. :)

**Pull request merged**
