### PR TITLE
[WIP] Italian translation

### PR DESCRIPTION
**Pull request by mattcav**
# Translation Progress

## Basic 

- [ ] `_data/translations.yml`
- [ ] `_data/languages.yml`

## Code (comments only)

- [x] `_includes/snippets`

## Readme

- [x] `README.md`

## Content

- [x] `_architecture.md`
- [x] `_author.md`
- [x] `_comments.md`
- [x] `_conditions.md`
- [x] `_contributing.md`
- [x] `_errors.md`
- [x] `_extend.md`
- [x] `_introduction.md`
- [x] `_loops.md`
- [x] `_mixins.md`
- [x] `_naming.md`
- [x] `_rwd.md`
- [x] `_sass.md`
- [x] `_syntax.md`
- [x] `_tldr.md`
- [x] `_toc.md`
- [ ] `_tools.md`
- [ ] `_variables.md`

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Great! Please, be sure to translate and fill the README as well. ;)

**Comment by mattcav** [comment]
Oh yes, sure. That was just my first attempt.

**Comment by HugoGiraudel** [comment]
Hello there. Do you have a rough estimation of the progress on your translation? :)

**Comment by mattcav** [comment]
ehm..I got a couple of guests during the past couple of weeks, so I haven't got so much free time.
Let's say that I can do from 3 to 5 files this week, and pretty much the same next week.

Closing it for the first week of september could be a reasonable forecast :)

**Comment by HugoGiraudel** [comment]
Hello. What is the current status? :)

**Comment by HugoGiraudel** [comment]
Hello there! It’s been 5 months since the latest update so I feel free to ask a few questions just to see how are things going. Are you still working or planning to work on this? Can I do anything to help you with this? :)

**Comment by mattcav** [comment]
Alright. Let me have a chat with @MakhBeth, that was offering help in september at from the front.
I will keep you posted, @HugoGiraudel

**Comment by HugoGiraudel** [comment]
Hey there. Little reminder that version 1.3 has been released! 🎉

You can either keep going on 1.2, then we merge, then you work on 1.3. Or go straight to 1.3 right away. It’s really up to you.

On topic, do you need me to find you any support on this? Or do you think you could find time and energy to finish it just the 2 of you? :)

**Comment by mattcav** [comment]
Ciao @HugoGiraudel.
Me & @MakhBeth are already on 1.3. We think we can deliver the entire translation by the end of the month (and announcing it ad CssDayIT)!

**Comment by HugoGiraudel** [comment]
Eccellente! Se posso fare qualcosa per aiutare… :)

**Comment by mattcav** [comment]
So @HugoGiraudel: the translation files are ready. You can find it here:
https://github.com/mattcav/sass-guidelines/tree/1.3.0
Give a look and let me know if I can help with something.

**Comment by HugoGiraudel** [comment]
Could you submit a PR? :)

**Comment by mattcav** [comment]
Et voilà, @HugoGiraudel. 
Actually, I cannot find `_data/translations.yml` and `_data/languages.yml`. Old / obsolete files?

**Comment by HugoGiraudel** [comment]
I think this can be closed. :P

**Pull request closed without merging**
