### PR TITLE
Update Polish translation to 1.2.0

### PR DESCRIPTION
**Pull request by klapec**
I hope everything's alright. Ping @matchabros.

BTW, I used https://github.com/HugoGiraudel/sass-guidelines/compare/e930a0c...0ed87b2 to compare the state from my last update with the latest commit. I think it's got everything in it, doesn't it? :)

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
That was fast. Terrific, thank you so much!

**Comment by HugoGiraudel** [comment]
Hey @klapec! Any chance you could update your translation with https://github.com/HugoGiraudel/sass-guidelines/pull/259 maybe?

**Comment by klapec** [comment]
Absolutely! I'm on it.

**Comment by klapec** [comment]
Done. #261

**Pull request merged**
