### PR TITLE
[RFR] 1.2.0

### PR DESCRIPTION
**Pull request by HugoGiraudel**

### CODE REVIEW

**Comment by morkro** [comment]
Any idea when `1.2.0` will be finished and we can start updating the translated pages? :)

**Comment by HugoGiraudel** [comment]
I will probably release is in August.

Le lun 20 juil. 2015 02:28, Moritz Kröger <notifications@github.com> a
écrit :

**Comment by HugoGiraudel** [comment]
Alright, I will release version 1.2.0 during the week. If anyone wants to have a look first to make sure everything is fine, that would be great. :)

**Comment by morkro** [comment]
:tada:

**Comment by HugoGiraudel** [comment]
Pay attention: the commit https://github.com/HugoGiraudel/sass-guidelines/commit/4a4488864dd18888239290f8dc95b444e78b82e9 about reworking the `@extend` section has been changed as part of a later pull-request: https://github.com/HugoGiraudel/sass-guidelines/pull/259. Be sure to translate the content of that latter PR as well.

**Pull request merged**
