### PR TITLE
Update translations.yml

### PR DESCRIPTION
**Pull request by Grawl**
Footer content – translate Hugo name and add translators here

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Actually if that's okay with you I'd like my name to remain in Latin, unless this is something really inappropriate in Russian.

**Comment by HugoGiraudel** [comment]
Ping @grawl.

**Comment by Grawl** [comment]
Regarding to our cyrillic-letters write system we always translate human names when possible. So, Albert Einstein in Russian will be “Альберт Эйнштейн”.

**Comment by HugoGiraudel** [comment]
Okay, I'm fine with that. Could you please rebase your branch perhaps?

**Comment by Grawl** [comment]
Oh I don't know how to rebase.

**Comment by HugoGiraudel** [comment]
Okay, I'll tackle this myself then. ;)

**Pull request merged**
