### PR TITLE
Updated Korean version to 1.1.0

### PR DESCRIPTION
**Pull request by kimdhoe**
Finally!

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
YAY! :)

**Comment by kimdhoe** [comment]
Hopefully I didn't miss anything.

**Comment by HugoGiraudel** [comment]
The title “Strings as CSS values” is not translated. Is it intended?

**Comment by kimdhoe** [comment]
Of course I missed something... I'll fix it now.

**Comment by kimdhoe** [comment]
Done.

**Comment by HugoGiraudel** [comment]
Thanks! Actually you forgot to replace code snippets with file includes but I did it. ;)

See: https://github.com/HugoGiraudel/sass-guidelines/commit/280407c1a858b38ef0c766a1aab462ec5823a433.

I'm glad to have the korean version in 1.1.0! \o/

**Comment by kimdhoe** [comment]
Aw I totally missed it. Sorry about that, and thanks for the work!

**Comment by HugoGiraudel** [comment]
Thank *you*. :)

**Comment by kimdhoe** [comment]
My pleasure. :)

**Comment by HugoGiraudel** [comment]
Stay tuned for 1.2.0! :P

**Pull request merged**
