### PR TITLE
[WIP] Portuguese version

### PR DESCRIPTION
**Pull request by magalhini**
Reviewed by me and also by @gnclmorais.

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Hey folks. What's the status on this? :)

**Comment by magalhini** [comment]
Still waiting for the pull requests. I'm going to merge @gnclmorais morais part today and sort out which conflicts we got. I'll ping the rest of the gang :)

**Comment by HugoGiraudel** [comment]
Hey my friends, what is the status?

**Comment by HugoGiraudel** [comment]
Hey folks, any progress? :)

**Comment by magalhini** [comment]
Sigh... no more pull requests. I talked with @gnclmorais today and we'll take over the rest of the translation ourselves, unfortunately. @HugoGiraudel, we are terribly sorry about this. We're likely going to grab the local repositories of what others have translated so far and merge the rest ourselves.

I assume many changes and updates have been made in the meantime, can you suggest us the correct way of getting those updates without losing too much of what we already translated?

**Comment by HugoGiraudel** [comment]
I am not sure what you are referring to. There have been a single content update to Sass Guidelines since the beginning, it's v1.1.0. There are not that many changes actually; you can see them in the relevant PR: https://github.com/HugoGiraudel/sass-guidelines/pull/125.

**Comment by gnclmorais** [comment]
Yeah, following @magalhini, we’ll pick this up as soon as possible and finish it, since nobody else chipped in on this.

**Comment by gnclmorais** [comment]
@HugoGiraudel, I just wrapped everything I could find and translate the rest so we can _finally_ present a first version! It’s on the [pull request](https://github.com/magalhini/sass-guidelines/pull/1) now, @magalhini will review it as soon as possible. :smiley:

**Comment by HugoGiraudel** [comment]
Can't wait! :)

**Comment by HugoGiraudel** [comment]
If it's good with you, pass the title in RFR rather than WIP. :)

**Comment by HugoGiraudel** [comment]
Missing: `pt` object in `_data/translations.yml`. Could you guys add it?

**Comment by HugoGiraudel** [comment]
Also, did you translate version 1.0.0 or did you include [changes from 1.1.0](https://github.com/HugoGiraudel/sass-guidelines/pull/125)?

**Comment by HugoGiraudel** [comment]
Also I have some sort of conflict here:

> <<<<<<< HEAD
> Não vamos entrar na discussão de organização de ficheiros nesta secção, mas discutiremos este tópico na [secção de arquitetura](#arquitetura).
> =======
> Não vamos entrar na discussão de organização de ficheiros nesta secção, mas discutiremos esse tópico na [secção de arquitetura](#arquitetura).
> >>>>>>> 7a0531e6a027c9229c146b51314d3e9f72795089

Which should I keep?

**Comment by magalhini** [comment]
@HugoGiraudel Ops, perhaps that file was missed entirely? I'll have a look soon and add it! Also I don't believe those changes were added... again, I'll have a look at 1.1.0 soon and see what else is missing!

About that conflict, sorry about that! It's only a one word change, but the latter is more correct, so you can use that one. In any case, both work well.

**Comment by HugoGiraudel** [comment]
@magalhini I'll merge my changes in `gh-pages` (although the version won't be released) just yet, and I'll tell you what's needed so we're all good. Give me 5 minutes. :)

**Comment by HugoGiraudel** [comment]
Alright. I just merged the current version (although I did a lot of things on it) in `gh-pages`. The version is not released yet, because we still have a few things to do:

* translate your block in `_data/translations.yml`
* take care of changes from 1.1.0
* have a final proof-read (ideally)

You should be able to open a PR from current `gh-pages` to take care of those last changes. :)

**Pull request merged**
