### PR TITLE
[RFR] Polish translation

### PR DESCRIPTION
**Pull request by klapec**
I hope I didn't screw things up this time :) This translation should be finished contentwise. There might be some errors here and there, but nothing too big. I encourage everyone who speaks Polish to review it.

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
This is terrific! We'll wait for a review before merging it. :)

**Comment by klapec** [comment]
Sure thing. I'll re-read it tomorrow morning as well.

**Comment by HugoGiraudel** [comment]
@klapec Hey Andrzej. I changed the way we work with partials to reduce the number of moving parts and code duplications. Could you please update your PR?

**Comment by klapec** [comment]
Done. I've managed to balls it up once again when updating my local branch but I think it's ok after all.

**Comment by HugoGiraudel** [comment]
Awesome

By the way, what do you think of this way of handling partials?

**Comment by klapec** [comment]
Thanks ;) I think it's a good idea, I like the idea of slicing up the markup in Jekyll whenever possible into partials and reusing them. :+1:

**Comment by klapec** [comment]
Also: big thanks to @matchabros for helping me ironing out all the errors we managed to catch.

**Comment by matchabros** [comment]
Thank you @klapec for the kind words, you did the majority but glad I could help out when you were in doubt.

**Comment by HugoGiraudel** [comment]
@klapec I am very truely sorry to ask you this, but I changed the translation system again for partials... Please accept my apologies. I think I found the best way to handle this at this point: https://github.com/HugoGiraudel/sass-guidelines/issues/96#issue-54613655.

Also, shall @Matchabros appear in the footer for the Polish translation?

**Comment by HugoGiraudel** [comment]
Note: `footer.content` in `_data/translation.yml` should be in Markdown. I will add a comment in `translations.yml` to warn against this.

**Comment by HugoGiraudel** [comment]
Done: https://github.com/HugoGiraudel/sass-guidelines/commit/c2829e38194b9b13d1e7f7ab95efb39de3b4b3b3.

**Comment by klapec** [comment]
Done as well :)

**Comment by HugoGiraudel** [comment]
Alright! Is it okay to be merged? :)

**Comment by klapec** [comment]
I think so, yes.

**Comment by HugoGiraudel** [comment]
Boom.

**Comment by klapec** [comment]
Awesome. My first PR ever. Thanks for the opportunity, it was fun!

**Pull request merged**
