### PR TITLE
[WIP] Croatian translation

### PR DESCRIPTION
**Pull request by andrejmlinarevic**
# Translation Progress
## Basic
- [x] `_data/translations.yml`
- [ ] `_data/languages.yml`
## Code (comments only)
- [ ] `_includes/snippets/`
## Readme
- [ ] `README.md`
## Content
- [x] `_architecture.md`
- [ ] `_author.md`
- [ ] `_comments.md`
- [ ] `_conditions.md`
- [ ] `_contributing.md`
- [ ] `_errors.md`
- [ ] `_extend.md`
- [ ] `_introduction.md`
- [ ] `_loops.md`
- [ ] `_mixins.md`
- [ ] `_naming.md`
- [ ] `_rwd.md`
- [ ] `_sass.md`
- [ ] `_syntax.md`
- [ ] `_tldr.md`
- [ ] `_toc.md`
- [ ] `_tools.md`
- [ ] `_variables.md`

### CODE REVIEW

**Comment by andrejmlinarevic** [comment]
@HugoGiraudel Croatian translation starting to happen! Could you take a look if everything is done right?

**Comment by HugoGiraudel** [comment]
So far, everything looks very good to me. Would it be okay for you to have a quick look at [CONTRIBUTING.md](https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/CONTRIBUTING.md) and especially [TRANSLATING.md](https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/TRANSLATING.md) (fresh from this morning) before moving on? :)

I'd recommend adding and translating the README.md file for your translation right away so that you can fill it during your translation. If you don't know wh

**Comment by andrejmlinarevic** [comment]
Well that's great! Glad I am on the right track, I'll check everything and continue with the work starting with the README.md ASAP. Thank you for your time!

**Comment by HugoGiraudel** [comment]
Hello there. Do you have a rough estimation of the progress on your translation? :)

**Comment by andrejmlinarevic** [comment]
@HugoGiraudel I've started translating a few more sections and will be complete soon, I hope I'll translate the most of it until the end of next week.

**Comment by HugoGiraudel** [comment]
That would be super nice. Keep me updated Andrej. :)

**Comment by HugoGiraudel** [comment]
Hello. What is the current status? :)

**Comment by HugoGiraudel** [comment]
Hello there! It’s been 5 months since the latest update so I feel free to ask a few questions just to see how are things going. Are you still working or planning to work on this? Can I do anything to help you with this? :)

**Comment by andrejmlinarevic** [comment]
Hi, 

thanks for being nice about this :) I had started working on this but it's gone a bit off the schedule and I cannot keep up with the updates that quickly. Let's keep it open and I will try to update my work so far with current documents and push the changes.

**Comment by HugoGiraudel** [comment]
Shall I look for other Croatian-speaking contributors to help you?

**Comment by HugoGiraudel** [comment]
Hey there. Little reminder that version 1.3 has been released! 🎉

You can either keep going on 1.2, then we merge, then you work on 1.3. Or go straight to 1.3 right away. It’s really up to you.

On topic, do you need me to find you any support on this? Or do you think you could find time and energy to finish it on your own? :)

**Comment by HugoGiraudel** [comment]
Hey @andrejmlinarevic. Is there any progress on this? Are you willing to continue or shall I close it? :)

**Comment by HugoGiraudel** [comment]
Hi! Shall I close this? :)

**Pull request closed without merging**
