### PR TITLE
[WIP] Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by jhonnymoreira**
# Translation Progress

## Basic

* [x] `_data/translations.yml`
* [ ] `_data/languages.yml`

## Code (comments only)

* [x] `_includes/snippets/`

## Readme

* [ ] `README.md`

## Content

* [x] `_architecture.md`
* [x] `_author.md`
* [ ] `_comments.md`
* [ ] `_conditions.md`
* [x] `_contributing.md`
* [ ] `_errors.md`
* [ ] `_extend.md`
* [x] `_introduction.md`
* [ ] `_loops.md`
* [ ] `_mixins.md`
* [ ] `_naming.md`
* [ ] `_rwd.md`
* [x] `_sass.md`
* [ ] `_syntax.md`
* [ ] `_tldr.md`
* [ ] `_toc.md`
* [ ] `_tools.md`
* [ ] `_variables.md`

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
PR: you are doing it right.

You're awesome

**Comment by jhonnymoreira** [comment]
@HugoGiraudel hahahaha thanks [=

**Comment by HugoGiraudel** [comment]
Amazing to see it progressing so fast. Can't wait to merge it. :)

**Comment by jhonnymoreira** [comment]
@HugoGiraudel probably today there'll be 2 more sections translated: `introduction` and `syntax`. Hope to finish until weekend [=

**Comment by jhonnymoreira** [comment]
@HugoGiraudel I'm without time this week. Hope to get to work next week. Sorry for that =/

**Comment by jhonnymoreira** [comment]
After a long long time, I'm able to get back where I stopped. [=

**Comment by HugoGiraudel** [comment]
Yay!

**Comment by HugoGiraudel** [comment]
(Added a few extra checkboxes to your PR description. :))

**Comment by jhonnymoreira** [comment]
Thank you <3

**Comment by HugoGiraudel** [comment]
Hey Jhonny! Any progress on this? :)

**Comment by HugoGiraudel** [comment]
Hello there. Do you have a rough estimation of the progress on your translation? :)

**Comment by jhonnymoreira** [comment]
Hi @HugoGiraudel. Sorry to vanish, I had no time since my last commits. I'll be off work from thursday (20/08), I expect to deliver the translation until saturday (22/08). [=

**Comment by rubiadias** [comment]
Oi @jhonnymoreira tudo bem? Muito boa a iniciativa ... Parabéns!
Se precisar de ajuda, ficaria feliz em tentar ajudar :P

**Comment by HugoGiraudel** [comment]
Hello. What is the current status? :)

**Comment by HugoGiraudel** [comment]
Hello there! It’s been 5 months since the latest update so I feel free to ask a few questions just to see how are things going. Are you still working or planning to work on this? Can I do anything to help you with this? :)

**Comment by jhonnymoreira** [comment]
@HugoGiraudel Hi, Hugo. Sorry for vanishing. I'll get back to the translation today! I missed a lot of things, for what I saw in my notifcation box. I'll dedicate the next 3 days to finish this, ok?

**Comment by jhonnymoreira** [comment]
@rubiadias Obrigado! Os próximos 3 dias estarei fazendo as tradućões. Creio que irei comećar do 0, pois não sei o quanto perdi!

**Comment by jhonnymoreira** [comment]
I'm gonna close this PR and open a new one with the 1.2 version.

**Comment by HugoGiraudel** [comment]
Alright. Tell me if I can do anything to help you.

**Comment by jhonnymoreira** [comment]
@HugoGiraudel Thanks! I'll continue here: #304

**Pull request closed without merging**
