### PR TITLE
Portuguese translation update

### PR DESCRIPTION
**Pull request by JLammeer**
Carefully, I have read and reproduced every missing commit from the changelog:

fireshot capture 3 - sass-guidelines_changelog md at master_ - https___github com_hugogiraudel_sas

Though, I'm affraid this won't be enough since the changelog seems to be out of date.

Aside of that, there were some commits I didn't have to reproduce since it was already done or didn't add any real change to the portuguese text:
- [_includes/snippets/extend/01/pt.html](https://github.com/HugoGiraudel/sass-guidelines/commit/4a44888#diff-8e36e1ae3c47d205c4674831bda3b8d8);
- [_includes/snippets/extend/02/pt.html](https://github.com/HugoGiraudel/sass-guidelines/commit/4a44888#diff-74288621e84e59081661cb5869d540b1);
- [en/_sass.md](https://github.com/HugoGiraudel/sass-guidelines/commit/67e7395#diff-9c37af33d99c372bd2924ab22c53ae3b).
  - The translation for "sibling" and "brother" is the same, in portuguese.

### CODE REVIEW

**Comment by JLammeer** [comment]
I did it, boys... I did it!
image

**Comment by HugoGiraudel** [comment]
Hey. I think you’ve done splendidly! The problem is probably on my side. I’ll check during my holidays (before the end of the month). I’ll let you know. ✨

**Comment by HugoGiraudel** [comment]
I’m currently having a look. It looks great! I’ll try to merge it this afternoon. :)

**Comment by morkro** [comment]
🎉

**Pull request merged**
