### PR TITLE
[RFR] Updated font files to include Cyrillic glyphs

### PR DESCRIPTION
**Pull request by HugoGiraudel**

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Ping @Grawl.

**Comment by Grawl** [comment]
Finally.
(But I can't convert it back to font file with [base64converter](http://base64converter.com/) like before… nevermind.)

**Comment by HugoGiraudel** [comment]
I did some custom set up on this. Is it a big deal that you can't convert it back?

**Comment by Grawl** [comment]
No, I did it just to check what glyphs is inside the font.
Just viewed the site at /ru and now cyrillic and latin letters are rendered with one font.

**Comment by HugoGiraudel** [comment]
So is it all good with you?

**Comment by Grawl** [comment]
All good now :) thank you for this great job again!

**Comment by HugoGiraudel** [comment]
Thank you for the help. :)

**Pull request merged**
