### PR TITLE
[RFR] Greek translation v1.2.0

### LINKED ISSUE #83: Greek translation
Ping @varemenos and @kmargaritis.

### PR DESCRIPTION
**Pull request by margaritis**
Closes #83

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Holy moly, that's cool. Let me review all this. :)

**Comment by HugoGiraudel** [comment]
Out of curiosity, why is the language code `el`?

**Comment by HugoGiraudel** [comment]
Am I right to assume you actually are up to date with 1.1.0 and not 1.2.0? Some changes from 1.2.0 do not seem to be taken into account. Or did I miss something?

**Comment by varemenos** [comment]
About the `gr` change to `el` there is a lot of controversy around this. We've started with `gr` but after some research we saw that most services and organizations (among them is even the European union) use the ISO 3166 codes for everything else except Greece `el` and United Kingdom `uk` so we've decided to change it. But I don't think anyone would mind if you'd want to stick with the ISO 3166 ones, so let me know which one you'd like to use.

I will contact the guys so we can get the rest of the issues sorted

**Comment by margaritis** [comment]
Sure thing Hugo. I can work on them tonight and i will update the PR.

**Comment by HugoGiraudel** [comment]
I really trust your judgement on this so if you think `el` is to be used, then let’s keep `el`.

**Comment by HugoGiraudel** [comment]
Alright, no worries. I am super excited to see this live. Tell me if I can do anything to help. :)

**Comment by margaritis** [comment]
:+1:

**Comment by margaritis** [comment]
I think the repo in sync Hugo! Let me know if anything is missing. :-)

**Comment by HugoGiraudel** [comment]
YAAAAAY! Thank you so much for your help folks.

Hug

1.3 is coming by the way. :D

**Comment by margaritis** [comment]
YAAAAAaaY!!! So happy and glad we have this live! Just great!

P.S. Bring it on -> v1.3. :hammer:

**Comment by varemenos** [comment]
Awesome, finally! Great job guys!
Thank you for your patients @HugoGiraudel, it only took us a year :stuck_out_tongue:

**Comment by margaritis** [comment]
Hey, it was just 2 days! The date on the issue it was just a Github malfunction. 16 Jan 2016 is the correct date, :stuck_out_tongue_closed_eyes: 

P.S. Great job everyone once again!

**Comment by HugoGiraudel** [comment]
One year but you did it. Thank you very much for your hard work. It’s great to have a Greek version. :)

**Pull request merged**
