### PR TITLE
[RFR] Czech translation

### PR DESCRIPTION
**Pull request by HugoGiraudel**
To do:

* [x] `README.md`
* [x] Content
* [x] `translations.yml`
* [x] `languages.yml`
* [ ] code snippets

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
@HoBi: merged. Thank you so much for your work.

**Comment by HoBi** [comment]
@HugoGiraudel I think it is broken somehow. It shows 'Warnings and Errors' section twice and does not show 'Contributing' at all...

**Comment by HugoGiraudel** [comment]
Woops! Thank you for spotting this. I'm very sorry. Now fixed.

**Comment by HugoGiraudel** [comment]
Ping @HoBi. Any idea when you'll have time to work on the code snippets? :)

**Pull request merged**
