### PR TITLE
Italian translations 1.3.0

### PR DESCRIPTION
**Pull request by mattcav**
Those are the markdown files for the Italian version of Sass Guidelines. 
@MakhBeth - take a look and raise a flag if something looks wrong.

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Do you mind creating a PR against `gh-pages`? `1.3.0` has been released 1.5 month ago, making it a bit behind the main branch.

**Comment by mattcav** [comment]
No prob. I will import it there.

**Comment by MakhBeth** [comment]
Nothing strange to report for me. I have a class of interns next month that will gladly debug :D

**Comment by HugoGiraudel** [comment]
Thank you.

**Comment by HugoGiraudel** [comment]
Without rushing you or anything guys, is there any chance you could submit a PR for your translation against the `gh-pages` branch so I can tackle this tomorrow? 

Thank you. :)

**Comment by HugoGiraudel** [comment]
Ah, didn’t know I could do it myself!

https://github.com/HugoGiraudel/sass-guidelines/pull/355

**Pull request closed without merging**
