### PR TITLE
add zh(Chinese) version

### PR DESCRIPTION
**Pull request by pinggod**

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Wow, this is amazing. I'll review it and merge it when I can. :)

**Comment by HugoGiraudel** [comment]
Thank you very much. :)

**Comment by HugoGiraudel** [comment]
Please, could you submit a PR to update this line: https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/_data/translations.yml#L120?

Adding something like ", translated by ..." in Chinese, with Markdown links would be nice. Kind of what has been done for the Polish translation: https://github.com/HugoGiraudel/sass-guidelines/blob/gh-pages/_data/translations.yml#L100.

**Comment by pinggod** [comment]
All right

**Pull request merged**
