### PR TITLE
[RFR] Updated Polish translation

### PR DESCRIPTION
**Pull request by klapec**
Marked as 1.1.0, although I've updated it in sync with the very latest commit - d69e75f2904f1ec0494990db87b0076296943b35

I hope everything is alright with this one, I'm sorry for the delay.

### CODE REVIEW

**Comment by klapec** [comment]
Looks like I've missed the snippets. Please hold with the merge, I'll update them ASAP.

**Comment by klapec** [comment]
Done.

**Comment by HugoGiraudel** [comment]
Awesome

**Comment by HugoGiraudel** [comment]
Thaaaanks! :)

**Comment by HugoGiraudel** [comment]
What is your Twitter handle?

**Comment by klapec** [comment]
@klapec_

**Pull request merged**
