### PR TITLE
Moved from double quotes to single quotes

### PR DESCRIPTION
**Pull request by HugoGiraudel**

### CODE REVIEW

**Comment by CrocoDillon** [comment]
+1 on single quotes, you don't need to hold down shift to create a single quote... though to be honest, I think that's hardly any effort and a lousy excuse :wink: But better a lousy excuse than no excuse at all!

Only using double quotes in JSON (because of spec) and HTML (because of habit).

**Comment by HugoGiraudel** [comment]
Done #57.

**Comment by mintuhouse** [comment]
I agree with the idea that single quotes are easier to type than double quotes but the default sass-convert which is used for beautification in several libraries generates double quotes by default. Do you know of any known work around for this?

**Comment by HugoGiraudel** [comment]
I guess the easiest way would be to do a quick search and replace after `sass-convert`.

**Comment by mintuhouse** [comment]
Thanks HugoGiraudel. Are you aware of any caveats with doing that? I mean special cases I need to take care of where double quotes are the only solution?

**Comment by HugoGiraudel** [comment]
Nope. None. :)

**Pull request closed without merging**
