### PR TITLE
Fixes tiny typo

### PR DESCRIPTION
**Pull request by mariusschulz**

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Thank you very much! :)

**Comment by mariusschulz** [comment]
Wow, that was quick. Rock on! :)

**Comment by HugoGiraudel** [comment]
> Wow, that was quick. 

That's what she said. :D

**Comment by mariusschulz** [comment]
As I said: rock on ;)

**Comment by HugoGiraudel** [comment]
After all those PRs fixing my mistakes, I hope we are close to none remaining. :)

**Comment by mariusschulz** [comment]
Don't worry, your guide was already great despite a couple of typos.

**Comment by HugoGiraudel** [comment]
Thank you very much Marius.

**Pull request merged**
