### PR TITLE
Update _sass.md

### PR DESCRIPTION
**Pull request by chroda**
A few words in portuguese that are wrong in according with the english version.

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Thank you very much!

**Comment by JLammeer** [comment]
@chroda Actually, that's just how the portuguese people talk to each other (dialect). Pretty weird, huh?! Though, they really helped this project. <3

**Comment by chroda** [comment]
@JLammeer hello, its all good? ;)
So.. I'm a Brazilian and to me, its is pretty weird, some words make no sense, I would to ask to @HugoGiraudel is this translate its is to be a portuguese from Portugal translation, so I have no expertise to help (because portuguese from Brasil is pretty different from Portugal).
---
I be happy to help to revise the entire document with proper time.
Just will be glad in have my name/github mentioned in this repo.

**Comment by JLammeer** [comment]
@chroda all good! =D

It has a mix of both dialects, though I don't think it is that hard to read. I mean: I've read it all with no problems.

However, if you think we should have a page for both dialects and our boy @HugoGiraudel support the idea, I would love to help you revise.

**Comment by chroda** [comment]
hey @JLammeer, I believe its not necessary to make another translation to PT-BR.
but it is important to notice temporal changes, and maybe minor words and confusing terms, I can revise this translation and u check is is okay in both dialects.
(I assuming here you speak pt-pt).

anyway, I'm available to improve and help this repo. <3

**Comment by JLammeer** [comment]
@chroda 

It seems like a great reason to modify the actual text:

> but it is important to notice temporal changes, and maybe minor words and confusing term

Though, u gotta be careful to use words and expressions that makes sense on both dialects. Otherwise, u will be modifying the text just for brazilians and then, maybe someone from another lusophone country will attempt to do the same. Therefore no one will ever be happy.

> I assuming here you speak pt-pt

Im from Brazil, just like you.

**Comment by chroda** [comment]
@JLammeer 
> Im from Brazil, just like you.
Thats so nice.
> Otherwise, u will be modifying the text just for brazilians.
Thats exactly my concern about it and the motivation to revise the words to the simplist way.
The main goal anyway its to provide the spread the information easily.

**Comment by HugoGiraudel** [comment]
Hey there! 👋 

I’d like to avoid having `pt-br` *and* a `pt-pt` translations, for maintainability reasons mostly. That being said, I agree with you that we need to make sure the content remains understandable in both languages. I’m happy merging any modifications you judge necessary.

One thing I suggest you do is updating the [Portuguese README.md](https://github.com/HugoGiraudel/sass-guidelines/tree/master/pages/pt) to include a note about the language in use and maybe how to keep it consistent and relevant both for Brazilian and non-Brazilian Portuguese.

What do you think?

**Comment by chroda** [comment]
Hey @HugoGiraudel, I beliave that is a good point to follow and be consistent about the translation, later I gonna update/do my considerations in the file.

Thanks for your support ;)

**Pull request merged**
