### PR TITLE
[RFR] Splitted the main content file into several sections

### PR DESCRIPTION
**Pull request by HugoGiraudel**

### CODE REVIEW

**Comment by dhoko** [comment]
giphy

This is better, isn't it ?

**Comment by HugoGiraudel** [comment]
My only concern is that if tomorrow, Sass adds a new feature and we want to add a new section, either we rename them all... Or we name it as 18. Mpf.

**Comment by dhoko** [comment]
Yup: *if*

> "Avec des si on mettrait Paris en bouteille" :v:

**Comment by HugoGiraudel** [comment]
At this point this is not conditional. Sass 3.5 will be released with new features, hence new sections will be added to Sass Guidelines.

**Comment by dhoko** [comment]
What about a yaml to describe the order ? So you don't need to set 1-Intro 2-xxx etc. You split chapters without any index.

Then you concat these files using the yaml to define the order.  (*You can add as many chapters you want with only one line to update, and have private sections waiting for 3.5 release*).

**Comment by HugoGiraudel** [comment]
Makes sense.

**Comment by HugoGiraudel** [comment]
There.

**Comment by HugoGiraudel** [comment]
I shall do the Polish version before merging this anyway. +@klapec

**Comment by HugoGiraudel** [comment]
@klapec May I ask you to review [this commit](https://github.com/HugoGiraudel/sass-guidelines/commit/6bdc122ed8c3936fd2de869f5c494d98ebe9efc8) to make sure I did not mess up anything please Andrzej? :)

**Comment by klapec** [comment]
Looks alright to me.

**Pull request merged**
